from __future__ import annotations

from typing import Protocol

from apps.gmo_bot.domain.model.types import BotConfig, DailyBalanceRecord, Pair, RunRecord, TradeRecord


class PersistencePort(Protocol):
    def get_current_config(self) -> BotConfig: ...

    def create_trade(self, trade: TradeRecord) -> None: ...

    def update_trade(self, trade_id: str, updates: dict) -> None: ...

    def get_trade(self, trade_id: str) -> TradeRecord | None: ...

    def find_open_trade(self, pair: Pair) -> TradeRecord | None: ...

    def count_trades_for_jst_day(self, pair: Pair, jst_day_start_iso: str, jst_day_end_iso: str) -> int: ...

    def count_trades_for_utc_day(self, pair: Pair, day_start_iso: str, day_end_iso: str) -> int: ...

    def list_recent_closed_trades(self, pair: Pair, limit: int) -> list[TradeRecord]: ...

    def save_daily_balance(self, snapshot: DailyBalanceRecord) -> None: ...

    def list_recent_daily_balances(self, days: int) -> list[DailyBalanceRecord]: ...

    def save_run(self, run: RunRecord) -> None: ...
