from __future__ import annotations

from typing import Protocol


class LockPort(Protocol):
    def acquire_runner_lock(self, ttl_seconds: int) -> bool: ...

    def release_runner_lock(self) -> None: ...

    def has_entry_attempt(self, bar_close_time_iso: str) -> bool: ...

    def mark_entry_attempt(self, bar_close_time_iso: str, ttl_seconds: int) -> bool: ...

    def clear_entry_attempt(self, bar_close_time_iso: str) -> None: ...

    def set_inflight_tx(self, signature: str, ttl_seconds: int) -> None: ...

    def has_inflight_tx(self, signature: str) -> bool: ...

    def clear_inflight_tx(self, signature: str) -> None: ...
