import type {
  ExecutionPort,
  SubmitSwapRequest,
  SwapConfirmation,
  SwapSubmission
} from '../../app/ports/execution_port';
import type { LoggerPort } from '../../app/ports/logger_port';
import type { JupiterQuoteClient } from './jupiter_quote_client';
import type { SolanaSender } from './solana_sender';

const SWAP_API_URL = 'https://lite-api.jup.ag/swap/v1/swap';

interface JupiterSwapResponse {
  swapTransaction: string;
}

export class JupiterSwapAdapter implements ExecutionPort {
  constructor(
    private readonly quoteClient: JupiterQuoteClient,
    private readonly solanaSender: SolanaSender,
    private readonly logger: LoggerPort
  ) {}

  async submitSwap(request: SubmitSwapRequest): Promise<SwapSubmission> {
    const quote = await this.quoteClient.fetchQuote(request);
    const swapTransaction = await this.fetchSwapTransaction(quote.raw);

    const txSignature = await this.solanaSender.sendVersionedTransactionBase64(swapTransaction);

    return {
      txSignature,
      inAmountAtomic: quote.inAmountAtomic,
      outAmountAtomic: quote.outAmountAtomic
    };
  }

  async confirmSwap(txSignature: string, timeoutMs: number): Promise<SwapConfirmation> {
    return this.solanaSender.confirmSignature(txSignature, timeoutMs);
  }

  private async fetchSwapTransaction(quoteResponse: Record<string, unknown>): Promise<string> {
    let response: Response;
    try {
      response = await fetch(SWAP_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          quoteResponse,
          userPublicKey: this.solanaSender.getPublicKey().toBase58(),
          wrapAndUnwrapSol: true
        })
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      throw new Error(`Jupiter swap request failed: ${errorMessage}`);
    }

    if (!response.ok) {
      throw new Error(`Jupiter swap failed: HTTP ${response.status}`);
    }

    const payload = (await response.json()) as Partial<JupiterSwapResponse>;
    if (!payload.swapTransaction) {
      throw new Error('Jupiter swap payload is missing swapTransaction');
    }

    this.logger.info('Swap transaction generated by Jupiter');
    return payload.swapTransaction;
  }
}
